export default {
	ping: './ping',
	game: './game',
	purge: './purge',
	lurk: './lurk',
	array: './array',
	help: './help',
	quotecommand: './quote',
	dadjoke: './dadjoke',
	uptime: './uptime',
	accountage: './accountage',
	followage: './followage',
	settitle: './settitle',
	setgame: './setgame',
	id: './id',
	games: './games',
	warframe: './warframe',
	socials: './socials',
	me: './me',
	vigor: './vigor',
	vip: './vip',
	unvip: './unvip',
	mod: './mod',
	unmod: './unmod',
	ban: './ban',
	shoutout: './shoutout'
};