name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run typecheck
        run: npm run typecheck

  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Ensure libssl1.1 is available (needed by mongodb-memory-server)
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl1.1 || {
            echo "libssl1.1 not available via apt, attempting to download focal package..."
            wget -q -O /tmp/libssl1.1.deb "http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.1/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb" || true
            if [ -f /tmp/libssl1.1.deb ]; then sudo dpkg -i /tmp/libssl1.1.deb || true; fi
          }

      - name: Install dependencies
        run: npm ci

      - name: Set MONGO_URI
        run: echo "MONGO_URI=mongodb://localhost:27017/test" >> $GITHUB_ENV

      - name: Typecheck (non-blocking)
        run: npm run typecheck || true

      - name: Run tests
        env:
          CI: true
        run: npm test --silent -- -i
